CREATE DATABASE web_day10;
USE web_day10;


CREATE TABLE PASSPORTS(
	ID INT NOT NULL AUTO_INCREMENT, 
    NUMBER VARCHAR(50) NOT NULL, 
    PRIMARY KEY ( ID )
);

CREATE TABLE FACULTIES (
	ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(70) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE STUDENTS(
	ID INT NOT NULL AUTO_INCREMENT, 
    NAME VARCHAR(50) NOT NULL, 
    ADDRESS VARCHAR(100),
    PASSPORT_ID INT NOT NULL,
    FACULTY_ID INT NOT NULL,
    PRIMARY KEY ( ID ),
    FOREIGN KEY (PASSPORT_ID) REFERENCES PASSPORTS (ID),
    FOREIGN KEY (FACULTY_ID) REFERENCES FACULTIES (ID)
);

CREATE TABLE SUBJECTS (
	ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);